language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install coveralls
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
script:
    - flake8 storops storops_test storops_comptest
    - "py.test -n2 --cov=storops --cov-config coverage.ini  --cov-report=xml --cov-report term --junit-xml=junit-result.xml storops_test"
#after_success:
#    - coveralls
notifications:
    email:
        - cedric.zhuang@emc.com
        - yue.zhao2@emc.com
        - peter.wang13@emc.com
        - tina.tang@emc.com
        - ryan.liang@emc.com
