language: python
python:
    - "3.10"
    - "3.11"
install:
    - pip install codecov
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
script:
    - flake8 storops storops_test storops_comptest
    - "py.test -n2 --cov=storops --cov-config coverage.ini  --cov-report=xml --cov-report term --junit-xml=junit-result.xml storops_test"
after_success:
    - codecov
notifications:
    email:
        - yong.huang@dell.com
