# Copyright (c) 2016 EMC Corporation.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

VNXLun:
  - name: read_iops
    counters: read_requests
  - name: read_iops_sp_a
    counters: read_requests_sp_a
  - name: read_iops_sp_b
    counters: read_requests_sp_b
  - name: write_iops
    counters: write_requests
  - name: write_iops_sp_a
    counters: write_requests_sp_a
  - name: write_iops_sp_b
    counters: write_requests_sp_b
  - name: read_mbps
    counters: blocks_read
    calculator: block_to_mbps
  - name: read_mbps_sp_a
    counters: blocks_read_sp_a
    calculator: block_to_mbps
  - name: read_mbps_sp_b
    counters: blocks_read_sp_b
    calculator: block_to_mbps
  - name: write_mbps
    counters: blocks_written
    calculator: block_to_mbps
  - name: write_mbps_sp_a
    counters: blocks_written_sp_a
    calculator: block_to_mbps
  - name: write_mbps_sp_b
    counters: blocks_written_sp_b
    calculator: block_to_mbps


VNXDisk:
  - name: read_iops
    counters: number_of_reads
  - name: write_iops
    counters: number_of_writes
  - name: read_mbps
    counters: kbytes_read
    calculator: kb_to_mbps
  - name: write_mbps
    counters: kbytes_written
    calculator: kb_to_mbps
  