on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Features:
            - TODO
            ## Fixed bugs:
            - TODO
            ## Misc:
            - TODO
            ## RPM related:
            **NOTE: If managing VNX system, install `python2-storops-vnx`. Download it from attachment.**
            ### RPM dependencies of `python2-storops`:
            - [PyYAML](http://cbs.centos.org/koji/packageinfo?packageID=48)
            - [python-bitmath >= 1.3.0](http://cbs.centos.org/koji/packageinfo?packageID=5174)
            - [python-cachez >= 0.1.2](http://cbs.centos.org/koji/packageinfo?packageID=5235)
            - [python-dateutil >= 2.4.2](http://cbs.centos.org/koji/packageinfo?packageID=4140)
            - [python-enum34](http://cbs.centos.org/koji/packageinfo?packageID=638)
            - [python-persist-queue >= 0.2.3](http://cbs.centos.org/koji/packageinfo?packageID=5249)
            - [python-requests >= 2.8.1](http://cbs.centos.org/koji/packageinfo?packageID=58)
            - [python-retryz >= 0.1.8](http://cbs.centos.org/koji/packageinfo?packageID=5234)
            - [python-six >= 1.9.0](http://cbs.centos.org/koji/packageinfo?packageID=175)
            ### RPM dependencies of `python2-storops-vnx`:
            - python-storops
            - `Unisphere CLI` rpm package, please contact with Dell EMC support about more detail. Or download from [here](https://github.com/emc-openstack/naviseccli).
          draft: false
          prerelease: ${{ contains(github.ref, 'dev') }}
